id: P010518
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4920
  title: དུས་འཁོར་རྩ་རྒྱུད་ལས་བསྡུས་པའི་རྒྱུད་ཀྱི་ཊཱི་ཀ་དྲི་མ་མེད་པའི་འོད།
  author: ''
  volumes:
    c5ac48c5ebf04bdd92439d952edbe4ce:
      image_group_id: I1KG5101
      title: ''
      volume_number: 1
      total_pages: 692
