id: P010518
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:53:50.504058
source_metadata:
  id: bdr:W1KG4920
  title: དུས་འཁོར་རྩ་རྒྱུད་ལས་བསྡུས་པའི་རྒྱུད་ཀྱི་ཊཱི་ཀ་དྲི་མ་མེད་པའི་འོད།
  author: ''
  volumes:
    c5ac48c5ebf04bdd92439d952edbe4ce:
      image_group_id: I1KG5101
      title: ''
      volume_number: 1
      total_pages: 692
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
