id: ICC678733
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T04:05:19+00:00'
last_modified: '2022-06-08T14:11:49.318375+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4920
  title: དུས་འཁོར་རྩ་རྒྱུད་ལས་བསྡུས་པའི་རྒྱུད་ཀྱི་ཊཱི་ཀ་དྲི་མ་མེད་པའི་འོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0DAA:
      image_group_id: I1KG5101
      title: ''
      total_pages: 692
      order: 1
      base_file: 0DAA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
